"use client";

import { useMemo, useState } from "react";
import Link from "next/link";
import { BN } from "@coral-xyz/anchor";
import { LAMPORTS_PER_SOL, PublicKey } from "@solana/web3.js";
import { useConnection, useWallet } from "@solana/wallet-adapter-react";
import { WalletMultiButton } from "@/components/wallet-button";
import { getProgram } from "@/lib/anchor";
import type { TgIntent } from "@/lib/tg-intent";

export default function TgCreateClient({ intent }: { intent: Extract<TgIntent, { t: "create" }> }) {
  const { connection } = useConnection();
  const { publicKey, signTransaction, signAllTransactions } = useWallet();

  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [message, setMessage] = useState<string | null>(null);
  const [result, setResult] = useState<{ id: string; vaultPda: string } | null>(null);

  const depositSol = useMemo(() => Number(intent.depositSol), [intent.depositSol]);
  const shareTotal = useMemo(() => intent.beneficiaries.reduce((s, b) => s + b.share, 0), [intent.beneficiaries]);

  async function onCreate() {
    if (!publicKey || !signTransaction) {
      setError("Connect the owner wallet first.");
      return;
    }

    if (publicKey.toBase58() !== intent.ownerAddress) {
      setError(`Connected wallet does not match intent owner (${intent.ownerAddress}).`);
      return;
    }

    if (!Number.isFinite(depositSol) || depositSol < 0) {
      setError("Invalid deposit amount.");
      return;
    }

    if (intent.beneficiaries.length < 1 || intent.beneficiaries.length > 5) {
      setError("Beneficiary count must be between 1 and 5.");
      return;
    }

    if (shareTotal !== 100) {
      setError(`Beneficiary shares must total 100 (got ${shareTotal}).`);
      return;
    }

    setLoading(true);
    setError(null);
    setMessage(null);

    try {
      const walletForAnchor = {
        publicKey,
        signTransaction,
        signAllTransactions: signAllTransactions ?? (async (txs: any[]) => Promise.all(txs.map(signTransaction))),
      };

      const program = getProgram(connection, walletForAnchor);
      const [vaultPda] = PublicKey.findProgramAddressSync([Buffer.from("vault"), publicKey.toBuffer()], program.programId);

      const parsedBeneficiaries = intent.beneficiaries.map((b) => ({
        address: new PublicKey(b.address),
        share: b.share,
        hasClaimed: false,
      }));

      await program.methods
        .initializeVault(new BN(intent.warningDays * 86400), new BN(intent.challengeDays * 86400), parsedBeneficiaries)
        .accounts({ vault: vaultPda, owner: publicKey })
        .rpc();

      if (depositSol > 0) {
        await program.methods
          .depositSol(new BN(Math.floor(depositSol * LAMPORTS_PER_SOL)))
          .accounts({ vault: vaultPda, owner: publicKey })
          .rpc();
      }

      const response = await fetch("/api/vaults", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          ownerAddress: intent.ownerAddress,
          vaultPda: vaultPda.toBase58(),
          warningPeriodDays: intent.warningDays,
          challengePeriodDays: intent.challengeDays,
          ownerEmail: null,
          telegramChatId: intent.chatId,
          beneficiaries: intent.beneficiaries.map((b) => ({ address: b.address, share: b.share, email: b.email })),
        }),
      });

      if (!response.ok) {
        const failure = await response.json().catch(() => ({ error: "Vault created on-chain, but DB save failed." }));
        throw new Error(failure.error || "Vault created on-chain, but DB save failed.");
      }

      const data = await response.json();
      setResult({ id: data.id, vaultPda: vaultPda.toBase58() });
      setMessage("Vault created. You can now use /status in Telegram.");
    } catch (e) {
      setError(e instanceof Error ? e.message : "Unexpected error");
    } finally {
      setLoading(false);
    }
  }

  return (
    <main className="shell grid">
      <section className="card grid">
        <h1 style={{ margin: 0 }}>Telegram: Create Vault</h1>
        <p style={{ color: "var(--muted)", margin: 0 }}>
          This link was generated by the Telegram bot. Connect the owner wallet and sign to create the vault.
        </p>
        <WalletMultiButton />
      </section>

      <section className="card grid">
        <p style={{ margin: 0 }}>
          Owner: <code>{intent.ownerAddress}</code>
        </p>
        <p style={{ margin: 0 }}>
          Warning: {intent.warningDays} days | Challenge: {intent.challengeDays} days
        </p>
        <p style={{ margin: 0 }}>Initial deposit: {intent.depositSol} SOL</p>
        <p style={{ margin: 0 }}>Beneficiaries: {intent.beneficiaries.length} (total share: {shareTotal}%)</p>

        <button className="button" onClick={onCreate} disabled={loading}>
          {loading ? "Creating..." : "Create Vault"}
        </button>

        {error && <p style={{ color: "#fca5a5" }}>{error}</p>}
        {message && <p style={{ color: "#86efac" }}>{message}</p>}

        {result && (
          <div className="card" style={{ margin: 0 }}>
            <p style={{ margin: 0, color: "var(--muted)" }}>Vault ID: {result.id}</p>
            <p style={{ margin: 0, color: "var(--muted)" }}>Vault PDA: {result.vaultPda}</p>
            <div style={{ display: "flex", gap: 12, flexWrap: "wrap" }}>
              <Link className="button" href={`/vault/${result.id}`} style={{ maxWidth: 220, textAlign: "center" }}>
                Open Dashboard
              </Link>
              <Link className="button" href="/vault" style={{ maxWidth: 220, textAlign: "center" }}>
                My Vaults
              </Link>
            </div>
          </div>
        )}
      </section>
    </main>
  );
}
